"""add medical and patient many-to-many

Revision ID: 5b33c62f8b4c
Revises: 3d868bce1445
Create Date: 2023-02-04 18:09:21.594324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b33c62f8b4c'
down_revision = '3d868bce1445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medical_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medical_id'], ['medical.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'medical_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_table('patient')
    op.drop_table('medical')
    # ### end Alembic commands ###
